TASK=${1}
SPARSITY=${2}


PRUNE_LOCATION=1,2,3,4,5,6,7,8,9,10,11
SUFFIX=None
EX_CATE=None
PRUNED_MODEL_PATH=out/${TASK}/s${SPARSITY}
# SUFFIX=sparsity${SPARSITY}
# EX_CATE=token_pruning_1201_${PRUNE_LOCATION}_lambda2x0.001_soft_50warmup_0.05init
# PRUNED_MODEL_PATH=out/$TASK/$EX_CATE/${TASK}_${SUFFIX}/best_acc0.8137_step7550_epoch65.65
PRUNING_TYPE=None # Setting the pruning type to be None for standard fine-tuning.
LEARNING_RATE=${3}
DISTILL_LAYER_LOSS_ALPHA=0.9
DISTILL_CE_LOSS_ALPHA=1.0
LAYER_DISTILL_VERSION=4
SPARSITY_EPSILON=0.01
DISTILLATION_PATH=out/${TASK}/${TASK}_full/best

bash scripts/run_FineTune.sh $TASK $SUFFIX $EX_CATE $PRUNING_TYPE $SPARSITY $DISTILLATION_PATH $DISTILL_LAYER_LOSS_ALPHA $DISTILL_CE_LOSS_ALPHA $LAYER_DISTILL_VERSION $SPARSITY_EPSILON $PRUNE_LOCATION $LEARNING_RATE $PRUNED_MODEL_PATH
